# Use latest Node 20 base image
FROM node:20

# Set working directory inside container
WORKDIR /app

# Copy package.json and install dependencies
COPY package.json .

RUN npm install

# Copy rest of the application files
COPY . .

# In dev we want "npm start"
CMD ["npm", "start"]
