version: "3.8"
services:
  mongodb:
    image: "mongo:8.0.10"
    container_name: mongodb
    volumes:
      - mongo-data:/data/db #Official MongoDB: /data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
  backend:
    container_name: goals-backend
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    image: goals-backend:${IMAGE_TAG}
    ports:
      - 8070:8070
    volumes:
      - logs:/app/logs
    depends_on:
      - mongodb
    env_file:
      - .env # For MONGO_*
      - ./backend/env/.env.backend # For APP_PORT
    restart: on-failure
  frontend:
    container_name: goals-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        IMAGE_TAG: ${IMAGE_TAG}
    image: goals-frontend:${IMAGE_TAG}
    ports:
      - 3000:80
    depends_on:
      - backend
  seed:
    container_name: seed-runner
    build:
      context: ./backend
      dockerfile: Dockerfile # Reusing backend image to run seeding script
    depends_on:
      - mongodb
    env_file:
      - .env # For MONGO_*
    command: ["node", "seed.js"] # Runs the seeding script
volumes:
  mongo-data:
  logs:
