version: "3.8"

services:
  backend:
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    build:
      context: /frontend
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src
      - /app/node_modules
    stdin_open: true
    tty: true
