version: "3.8"
services:
  mongodb:
    image: "mongo:8.0.10"
    container_name: mongodb
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./backend/.env
  backend:
    container_name: goals-backend
    # build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8070:8070
    volumes:
      - logs:/app/logs
      - ./backend:/app #relative path - Mount source code for development
      - /app/node_modules # Prevent overwrite of node_modules
    depends_on:
      - mongodb
  frontend:
    container_name: goals-frontend
    # build: ./backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:80
    volumes:
      - ./frontend/src:/app/src #relative path - Enable live reload
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
  seed:
    container_name: seed-runner
    build:
      context: ./backend
      dockerfile: Dockerfile # Reusing backend image to run seeding script
    depends_on:
      - mongodb
    env_file:
      - ./backend/.env
    command: ["node", "seed.js"] # Runs the seeding script
volumes:
  mongo-data:
  logs:
