version: "3.8"
services:
  mongodb:
    image: "mongo:8.0.10"
    volumes:
      - mongo-data:/data/db
    env_file:
      - ./backend/.env
  backend:
    # build: ./backend
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - 8070:8070
    volumes:
      - logs:/app/logs
      - ./backend:/app #relative path
      - /app/node_modules
    depends_on:
      - mongodb
  frontend:
    # build: ./backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend/src:/app/src #relative path
      - /app/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - backend
volumes:
  mongo-data:
  logs:
